apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-conten
  namespace: blog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocp-nas-sc-gold
