---
apiVersion: v1
kind: Service
metadata:
  name: svc-for-myblog
  namespace: blog
spec:
  type: LoadBalancer
  selector:
    app: myblog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
    

